cart/urls.py
from django.urls import path, re_path
from cart import views as cart

urlpatterns = [
    path(r'', cart.cart),
    re_path(r'add_cart_(\d+)_(\d+)/', cart.add_cart),
    re_path(r'delete_(\d+)/', cart.delete_cart),
    re_path(r'num_change_(\d+)_(\w+)_(\d+)', cart.num_change),
]

dailyfresh/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from user import urls as user
from goods import urls as goods
from cart import urls as cart
from order import urls as order
from goods import views

urlpatterns = [
    path(r'', views.home),
    path(r'admin/', admin.site.urls),
    path(r'user/', include(user)),
    path(r'goods/', include(goods)),
    path(r'tinymce/', include('tinymce.urls')),
    path(r'cart/', include(cart)),
    path(r'order/', include(order)),
]

user/urls.py
from django.contrib import admin
from django.urls import path, re_path
from user import views

urlpatterns = [
    path(r'register/', views.register),
    path(r'register_exist/', views.register_exist),
    path(r'login/', views.login),
    path(r'info/', views.info),
    path(r'order/', views.order),
    path(r'site/', views.site),
    path(r'logout/', views.logout),

]

order/models.py
from django.db import models

# Create your models here.

class Order(models.Model):
    order_id = models.CharField(max_length=20, primary_key=True)
    user = models.ForeignKey('user.User', on_delete=models.CASCADE)
    date = models.DateTimeField(auto_now=True)
    is_pay = models.IntegerField(default=0)
    total = models.DecimalField(max_digits=6, decimal_places=2)
    address = models.CharField(max_length=150, default='')
    pay = models.IntegerField(default=0)


class OrderDetail(models.Model):
    goods = models.ForeignKey('goods.Goods', on_delete=models.CASCADE)
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=5, decimal_places=2)
    count = models.IntegerField()

user/models.py
from django.db import models

# Create your models here.

class User(models.Model):
    name = models.CharField(max_length=30)
    password = models.CharField(max_length=52)
    telephone = models.CharField(max_length=11, default="")
    address = models.CharField(max_length=100, default="")
    email = models.CharField(max_length=30,)
    zip_code = models.CharField(max_length=6, default="")
    receive_user = models.CharField(max_length=100, default="")

    def __str__(self):
        return self.name

user/views.py
from django.shortcuts import render, HttpResponse, redirect, HttpResponseRedirect
from user.models import User
from hashlib import sha1
from django.http import JsonResponse
from .decorators import login_required
from goods.models import Goods
from order.models import Order,OrderDetail
from cart.models import Cart
from django.core.paginator import Paginator

# Create your views here.

def register(request):
    if request.method == "POST":
        username = request.POST.get("user_name")
        password1 = request.POST.get("password")
        password2 = request.POST.get("password2")
        email = request.POST.get("email")
        if password1 == password2:
            hash = sha1()
            hash.update(password2.encode("utf8"))
            password = hash.hexdigest()
            user = User(name=username, password=password, email=email)
            user.save()
            return redirect("/user/login/")
    else:
        return render(request, "user/register.html")

def register_exist(request):
    username = request.GET.get('username')
    count = User.objects.filter(name=username).count()
    return JsonResponse({'count': count})

def login(request):
    if request.method == "POST":
        username = request.POST.get("username")
        password = request.POST.get("password")
        remember = request.POST.get("remember", 0)
        user = User.objects.filter(name=username)
        if len(user) == 1:
            hash = sha1()
            hash.update(password.encode("utf8"))
            password_hash = hash.hexdigest()
            if password_hash == user[0].password:
                request.session["user_id"] = user[0].id
                request.session["username"] = user[0].name
                cart_count = Cart.objects.filter(user=user[0])
                request.session["cart_count"] = len(cart_count)
                red = HttpResponseRedirect("/goods/home/")
                if remember == 1:
                    red.set_cookie("username", username.encode('utf-8').decode('latin-1'))
                else:
                    red.set_cookie('username', '', max_age=-1)
                return red
            else:
                username = request.COOKIES.get("username", "")
                username = username.encode('latin-1').decode('utf-8')
                context = {
                    'error_name': 0, 'error_password': 1, 'username': username,
                }
                return render(request, "user/login.html", context)
        else:
            username = request.COOKIES.get("username", "")
            username = username.encode('latin-1').decode('utf-8')
            context = {
                'error_name': 1, 'error_password': 0, 'username': username,
            }
            return render(request, "user/login.html", context)
    else:
        return render(request, "user/login.html")

def logout(request):
    request.session.flush()
    return redirect('/goods/home/')


@login_required
def info(request):
    user_id = request.session.get("user_id","")
    if user_id == "":
        redirect("/user/login/")
    else:
        user = User.objects.get(id=user_id)
        recent_goods = "recent_goods_%s" % user_id
        recent = request.COOKIES.get(recent_goods, "")
        recent = recent.split(",")
        recent_list = []
        for id in recent:
            try:
                goods = Goods.objects.get(id=id)
                recent_list.append(goods)
            except:     # 如果最近浏览不存在则忽略此商品
                pass

        context = {
            'username': user.name,
            'email': user.email,
            'address': user.address,
            'recent_list': recent_list,
        }
        return render(request, "user/user_center_info.html", context)

@login_required
def order(request):
    user_id = request.session.get("user_id")
    order = Order.objects.filter(user_id=user_id).order_by("-date")
    context = {
        'orders': order,
    }
    return render(request, "user/user_center_order.html",context)

def site(request):
    user_id = request.session.get("user_id")
    if request.method == "POST":
        receive_user = request.POST.get("receive_user")
        address = request.POST.get("address")
        telephone = request.POST.get("telephone")
        zip_code = request.POST.get("zip_code")
        user = User.objects.get(id=user_id)
        user.telephone = telephone
        user.zip_code = zip_code
        user.address = address
        user.receive_user = receive_user
        user.save()
        return redirect("/user/site/")
    else:
        user = User.objects.get(id=user_id)
        context = {
            'user': user,
            'telephone': user.telephone[:3]+"****"+user.telephone[-4:],
        }
        return render(request, "user/user_center_site.html", context)

templates/user/base.html
{% extends "base.html" %}

{% block body2 %}
	<div class="search_bar clearfix">
		<a href="/goods/home/" class="logo fl"><img src="/static/images/logo.png"></a>
		<div class="sub_page_name fl">|&nbsp;&nbsp;&nbsp;&nbsp;用户中心</div>
		<div class="search_con fr">
			<input type="text" class="input_text fl" name="" placeholder="搜索商品">
			<input type="button" class="input_btn fr" name="" value="搜索">
		</div>
	</div>
{% endblock body2 %}

templates/user/login.html
{% extends "base_bottom.html" %}
{% block title %}登录{% endblock title %}
{% block head %}
<script>
    $(function () {
        name_error=true
        pwd_error=true
        if($('.name_input').val().length!=0){
            name_error = false
        }
        if($('.pwd_error').val().length!=0){
            pwd_error = false
        }



        if({{ error_name }}== 1){
            $('.user_error').html('用户名错误').show();
        }
        if({{ error_password }}== 1){
            $('.pwd_error').html('密码错误').show()
        }
        $('.name_input').blur(function () {
            if($('.name_input').val().length==0){
                $('.user_error').html('请填写用户名').show();
                name_error=true;
            }else {
                $('.user_error').hide()
                name_error=false;
            }

        })
        $('.pass_input').blur(function () {
            if($('.pass_input').val().length==0){
                $('.pwd_error').html('请写密码').show();
                pwd_error=true
            }
            else {$('.pwd_error').hide()
                pwd_error=false}
        })

        $(":submit[id=lo]").click(function(check){
            console.log(pwd_error,name_error)
        if(pwd_error==true || name_error==true){
           check.preventDefault();//此处阻止提交表单
        }
    });

    })
    </script>
{% endblock head %}
{% block body %}
	<div class="login_top clearfix">
		<a href="/goods/home/" class="login_logo"><img src="/static/images/logo02.png"></a>
	</div>

	<div class="login_form_bg">
		<div class="login_form_wrap clearfix">
			<div class="login_banner fl"></div>
			<div class="slogan fl">日夜兼程 · 急速送达</div>
			<div class="login_form fr">
				<div class="login_title clearfix">
					<h1>用户登录</h1>
					<a href="/user/register/">立即注册</a>
				</div>
				<div class="form_input">
					<form action="/user/login/" method="post">
						{%csrf_token%}
						<input type="text" name="username" class="name_input" value="{{ username }}" placeholder="请输入用户名">
						<div class="user_error">输入错误</div>
						<input type="password" name="password" class="pass_input" placeholder="请输入密码">
						<div class="pwd_error">输入错误</div>
						<div class="more_input clearfix">
							<input type="checkbox" name="remember" value="1">
							<label>记住用户名</label>
							<a href="#">忘记密码</a>
						</div>
						<input type="submit" name="" value="登录" class="input_submit">
					</form>
				</div>
			</div>
		</div>
	</div>
{% endblock body %}

templates/user/register.html
{% extends "base_bottom.html" %}
{% block title %}注册{% endblock title %}
{% block head %}
<script type="text/javascript" src="/static/js/register.js"></script>
{% endblock head %}
{% block body %}
<div class="register_con">
	<div class="l_con fl">
		<a class="reg_logo"><img src="/static/images/logo02.png"></a>
		<div class="reg_slogan">足不出户  ·  新鲜每一天</div>
		<div class="reg_banner"></div>
	</div>

	<div class="r_con fr">
		<div class="reg_title clearfix">
			<h1>用户注册</h1>
			<a href="/user/login/">登录</a>
		</div>
		<div class="reg_form clearfix">
			<form action="/user/register/" method="post">
				{%csrf_token%}
			<ul>
				<li>
					<label>用户名:</label>
					<input type="text" name="user_name" id="user_name">
					<span class="error_tip">提示信息</span>
				</li>
				<li>
					<label>密码:</label>
					<input type="password" name="password" id="pwd">
					<span class="error_tip">提示信息</span>
				</li>
				<li>
					<label>确认密码:</label>
					<input type="password" name="password2" id="cpwd">
					<span class="error_tip">提示信息</span>
				</li>
				<li>
					<label>邮箱:</label>
					<input type="text" name="email" id="email">
					<span class="error_tip">提示信息</span>
				</li>
				<li class="agreement">
					<input type="checkbox" name="allow" id="allow" checked="checked">
					<label>同意”天天生鲜用户使用协议“</label>
					<span class="error_tip2">提示信息</span>
				</li>
				<li class="reg_sub">
					<input type="submit" value="注 册">
				</li>
			</ul>
			</form>
		</div>

	</div>

</div>
{% endblock body %}


	

templates/user/user_center_info.html
{% extends 'user/base.html' %}
{% block title %}用户中心{% endblock title %}
{% block head %}{% endblock head %}

{% block body %}

	<div class="main_con clearfix">
		<div class="left_menu_con clearfix">
			<h3>用户中心</h3>
			<ul>
				<li><a href="" class="active">· 个人信息</a></li>
				<li><a href="/user/order/">· 全部订单</a></li>
				<li><a href="/user/site/">· 收货地址</a></li>
			</ul>
		</div>
		<div class="right_content clearfix">
				<div class="info_con clearfix">
				<h3 class="common_title2">基本信息</h3>
						<ul class="user_info_list">
							<li><span>用户名：</span>{{ username }}</li>
							<li><span>联系方式：</span>{{ email }}</li>
							<li><span>联系地址：</span>{{ address }}</li>
						</ul>
				</div>
				
				<h3 class="common_title2">最近浏览</h3>
				<div class="has_view_list">
					<ul class="goods_type_list clearfix">

					{% for goods in recent_list %}
					<li>
						<a href="/goods/detail_{{ goods.type.name }}_{{ goods.id }}"><img src="/static/{{ goods.picture }}"></a>
						<h4><a href="detail.html">{{ goods.name }}</a></h4>
						<div class="operate">
							<span class="prize">￥{{ goods.price }}</span>
							<span class="unit">{{ goods.price }}/{{ goods.unit }}</span>
							<a href="javascript:;" class="add_goods" onclick="add_cart({{ goods.id }})" title="加入购物车"></a>
						</div>
					</li>
					{% endfor %}


			</ul>
		</div>
		</div>
	</div>


<script>
		<!--添加购物车 ajax-->
		function add_cart(goods_id){
		var xhr;
		if(window.XMLHttpRequest){
		xhr = new XMLHttpRequest();
		}
		url ="/cart/add_cart_"+goods_id+"_1";
		xhr.open("GET",url,true);

		xhr.onreadystatechange=function(){

		if(xhr.readyState == 4 && xhr.status == 200){
			var data = xhr.responseText;
			data = JSON.parse(data);
			document.getElementById("show_count").innerHTML=data.cart_count;
			}
		}
		xhr.send();
		pop_success()
		}

		function pop_success(){
			alert("添加成功！")
		}

</script>

{% endblock body %}

templates/user/user_center_order.html
{% extends 'user/base.html' %}
{% block title %}用户中心{% endblock title %}
{% block head %}{% endblock head %}

{% block body %}



	<div class="main_con clearfix">
		<div class="left_menu_con clearfix">
			<h3>用户中心</h3>
			<ul>
				<li><a href="/user/info/">· 个人信息</a></li>
				<li><a href="" class="active">· 全部订单</a></li>
				<li><a href="/user/site/">· 收货地址</a></li>
			</ul>
		</div>


		<div class="right_content clearfix">
				<h3 class="common_title2">全部订单</h3>

					{% for order in orders %}
				<ul class="order_list_th w978 clearfix">
					<li class="col01">{{ order.date }}</li>
					<li class="col02">订单号：{{ order.order_id }}</li>
					{% if order.is_pay == 1 %}
					<li class="col02 stress" id="pay_status_{{ order.order_id }}">已支付</li>
					{% else %}
					<li class="col02 stress" id="pay_status_{{ order.order_id }}">未支付</li>
					{% endif %}
				</ul>
				<table class="order_list_table w980">
					<tbody>
						<tr>
							<td width="55%">

								{% for order_detail in order.orderdetail_set.all %}
								<ul class="order_goods_list clearfix">					
									<li class="col01"><img src="/static/{{ order_detail.goods.picture }}"></li>
									<li class="col02">{{ order_detail.goods.name }}<em>{{ order_detail.goods.price }}元/{{ order_detail.goods.unit }}</em></li>
									<li class="col03">{{ order_detail.count }}</li>
									<li class="col04">{{ order_detail.price }}元</li>
								</ul>
								{% endfor %}

							</td>
							<td width="15%">{{ order.total }}元</td>
							{% if order.is_pay == 1 %}
							<td width="15%">已付款</td>
							<td width="15%"><a href="javascript:;" class="oper_btn" >查物流</a></td>
							{% else %}
							<td width="15%">待付款</td>
							<td width="15%"><a href="javascript:;" class="oper_btn" id="to_pay_{{ order.order_id }}" onclick="pay({{order.order_id}})">去付款</a></td>
							{% endif %}
						</tr>
					</tbody>
				</table>
				{% endfor %}
			{% if not orders %}
				<br>
				<br>
				<p style="font-size:20px;text-align:center;">空空如也</p>
				<br>
				<br>
			{% endif %}
				<!--<div class="pagenation">-->
					<!--<a href="#"><上一页</a>-->
					<!--<a href="#" class="active">1</a>-->
					<!--<a href="#">2</a>-->
					<!--<a href="#">3</a>-->
					<!--<a href="#">4</a>-->
					<!--<a href="#">5</a>-->
					<!--<a href="#">下一页></a>-->
				<!--</div>-->
		</div>
	</div>
<script>

		function pay(id){
		status = "pay_status_"+id;
		to_pay = "to_pay_"+id;
		if(document.getElementById(status).innerHTML == "未支付"){
		var xhr;
		if(window.XMLHttpRequest){
		xhr = new XMLHttpRequest();
		}
		url ="/order/pay_"+id;
		xhr.open("GET",url,true);

		xhr.onreadystatechange=function(){

		if(xhr.readyState == 4 && xhr.status == 200){
			var data = xhr.responseText;
			data = JSON.parse(data);
			document.getElementById(status).innerHTML=data.status;
			document.getElementById(to_pay).innerHTML="查物流";
			alert("支付成功！")
			}
		}
		xhr.send();
		}
		}
</script>

{% endblock body %}

templates/user/user_center_site.html
{% extends 'user/base.html' %}
{% block title %}用户中心{% endblock title %}
{% block head %}{% endblock head %}

{% block body %}



	<div class="main_con clearfix">
		<div class="left_menu_con clearfix">
			<h3>用户中心</h3>
			<ul>
				<li><a href="/user/info/">· 个人信息</a></li>
				<li><a href="/user/order/">· 全部订单</a></li>
				<li><a href="" class="active">· 收货地址</a></li>
			</ul>
		</div>
		<div class="right_content clearfix">
				<h3 class="common_title2">收货地址</h3>
				<div class="site_con">
					<dl>
						<dt>当前地址：</dt>
						<dd>{{ user.address }}	{{ user.receive_user }}(收)	电话：{{ telephone }}</dd>
					</dl>					
				</div>
				<h3 class="common_title2">编辑地址</h3>
				<div class="site_con">
					<form action="/user/site/" method="post">
						<div class="form_group">
							<label>收件人：</label>
							<input type="text" name="receive_user">
						</div>
						<div class="form_group form_group2">
							<label>详细地址：</label>
							<textarea class="site_area" name="address"></textarea>
						</div>
						<div class="form_group">
							<label>邮编：</label>
							<input type="text" name="zip_code">
						</div>
						<div class="form_group">
							<label>手机：</label>
							<input type="text" name="telephone">
						</div>
						{% csrf_token %}
						<input type="submit" name="" value="提交" class="info_submit">
					</form>
				</div>
		</div>
	</div>


{% endblock body %}